### ISSUE TITLE
LP

### ISSUE THREAD

**Issue by fune0** [fune0/Oruga#1]
# ユーザーストーリー
ユーザーがチャット形式のシンプルなUIにたどり着ける

# 詳細
チャット画面まわりのデザインを決める
Orugaの使い方を表示する（js：ボタン非表示）
CSSをレスポンシブ対応にする（js：レスポンシブ）

# ストーリーポイント
ひと目でわかるシンプルかつスタイリッシュなデザイン

# 満足条件
- [ ] シンプルかつスタイリッシュなデザイン
- [ ] ブラウザを開いたまま使えるような仕様

**Comment by Kenminami** [comment]
![oruga](https://user-images.githubusercontent.com/46950910/53326045-f5b07200-3927-11e9-8d9e-14216af33765.jpg)

**Comment by namanakamura** [comment]
# jsで表示/非表示にする説明文(仮)
お疲れ様！
知りたい単語を聞いてね！
簡単な解説と詳しいページのリンクを答えるよ！
ウインドウを縮めて使ってね！いも虫だけに！

**Comment by masato-github** [comment]
[チーム開発フォルダ.zip](https://github.com/fune0/Oruga/files/2908380/default.zip)

**Comment by masato-github** [comment]
[manual表示:非表示.zip](https://github.com/fune0/Oruga/files/2908382/manual.zip)
説明文　表示非表示の仕組みのサンプルです
確認してみてください
